name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn --pure-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Unit testing
        run: yarn test:ci
      - name: Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
